// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker_service.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShutDownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutDownRequest) Reset()         { *m = ShutDownRequest{} }
func (m *ShutDownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutDownRequest) ProtoMessage()    {}
func (*ShutDownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{0}
}

func (m *ShutDownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutDownRequest.Unmarshal(m, b)
}
func (m *ShutDownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutDownRequest.Marshal(b, m, deterministic)
}
func (m *ShutDownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutDownRequest.Merge(m, src)
}
func (m *ShutDownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutDownRequest.Size(m)
}
func (m *ShutDownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutDownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutDownRequest proto.InternalMessageInfo

type ShutDownResponse struct {
	IterationNum         int32    `protobuf:"varint,1,opt,name=iterationNum,proto3" json:"iterationNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutDownResponse) Reset()         { *m = ShutDownResponse{} }
func (m *ShutDownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutDownResponse) ProtoMessage()    {}
func (*ShutDownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{1}
}

func (m *ShutDownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutDownResponse.Unmarshal(m, b)
}
func (m *ShutDownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutDownResponse.Marshal(b, m, deterministic)
}
func (m *ShutDownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutDownResponse.Merge(m, src)
}
func (m *ShutDownResponse) XXX_Size() int {
	return xxx_messageInfo_ShutDownResponse.Size(m)
}
func (m *ShutDownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutDownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutDownResponse proto.InternalMessageInfo

func (m *ShutDownResponse) GetIterationNum() int32 {
	if m != nil {
		return m.IterationNum
	}
	return 0
}

type ExchangeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeRequest) Reset()         { *m = ExchangeRequest{} }
func (m *ExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangeRequest) ProtoMessage()    {}
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{2}
}

func (m *ExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRequest.Unmarshal(m, b)
}
func (m *ExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRequest.Marshal(b, m, deterministic)
}
func (m *ExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRequest.Merge(m, src)
}
func (m *ExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangeRequest.Size(m)
}
func (m *ExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRequest proto.InternalMessageInfo

type ExchangeResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeResponse) Reset()         { *m = ExchangeResponse{} }
func (m *ExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*ExchangeResponse) ProtoMessage()    {}
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{3}
}

func (m *ExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeResponse.Unmarshal(m, b)
}
func (m *ExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeResponse.Marshal(b, m, deterministic)
}
func (m *ExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeResponse.Merge(m, src)
}
func (m *ExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_ExchangeResponse.Size(m)
}
func (m *ExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeResponse proto.InternalMessageInfo

func (m *ExchangeResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type PEvalRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PEvalRequest) Reset()         { *m = PEvalRequest{} }
func (m *PEvalRequest) String() string { return proto.CompactTextString(m) }
func (*PEvalRequest) ProtoMessage()    {}
func (*PEvalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{4}
}

func (m *PEvalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PEvalRequest.Unmarshal(m, b)
}
func (m *PEvalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PEvalRequest.Marshal(b, m, deterministic)
}
func (m *PEvalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PEvalRequest.Merge(m, src)
}
func (m *PEvalRequest) XXX_Size() int {
	return xxx_messageInfo_PEvalRequest.Size(m)
}
func (m *PEvalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PEvalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PEvalRequest proto.InternalMessageInfo

type PEvalResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PEvalResponse) Reset()         { *m = PEvalResponse{} }
func (m *PEvalResponse) String() string { return proto.CompactTextString(m) }
func (*PEvalResponse) ProtoMessage()    {}
func (*PEvalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{5}
}

func (m *PEvalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PEvalResponse.Unmarshal(m, b)
}
func (m *PEvalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PEvalResponse.Marshal(b, m, deterministic)
}
func (m *PEvalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PEvalResponse.Merge(m, src)
}
func (m *PEvalResponse) XXX_Size() int {
	return xxx_messageInfo_PEvalResponse.Size(m)
}
func (m *PEvalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PEvalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PEvalResponse proto.InternalMessageInfo

func (m *PEvalResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type IncEvalRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncEvalRequest) Reset()         { *m = IncEvalRequest{} }
func (m *IncEvalRequest) String() string { return proto.CompactTextString(m) }
func (*IncEvalRequest) ProtoMessage()    {}
func (*IncEvalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{6}
}

func (m *IncEvalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncEvalRequest.Unmarshal(m, b)
}
func (m *IncEvalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncEvalRequest.Marshal(b, m, deterministic)
}
func (m *IncEvalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncEvalRequest.Merge(m, src)
}
func (m *IncEvalRequest) XXX_Size() int {
	return xxx_messageInfo_IncEvalRequest.Size(m)
}
func (m *IncEvalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncEvalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncEvalRequest proto.InternalMessageInfo

type IncEvalResponse struct {
	Update               bool     `protobuf:"varint,1,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncEvalResponse) Reset()         { *m = IncEvalResponse{} }
func (m *IncEvalResponse) String() string { return proto.CompactTextString(m) }
func (*IncEvalResponse) ProtoMessage()    {}
func (*IncEvalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{7}
}

func (m *IncEvalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncEvalResponse.Unmarshal(m, b)
}
func (m *IncEvalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncEvalResponse.Marshal(b, m, deterministic)
}
func (m *IncEvalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncEvalResponse.Merge(m, src)
}
func (m *IncEvalResponse) XXX_Size() int {
	return xxx_messageInfo_IncEvalResponse.Size(m)
}
func (m *IncEvalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncEvalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncEvalResponse proto.InternalMessageInfo

func (m *IncEvalResponse) GetUpdate() bool {
	if m != nil {
		return m.Update
	}
	return false
}

type AssembleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssembleRequest) Reset()         { *m = AssembleRequest{} }
func (m *AssembleRequest) String() string { return proto.CompactTextString(m) }
func (*AssembleRequest) ProtoMessage()    {}
func (*AssembleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{8}
}

func (m *AssembleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssembleRequest.Unmarshal(m, b)
}
func (m *AssembleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssembleRequest.Marshal(b, m, deterministic)
}
func (m *AssembleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssembleRequest.Merge(m, src)
}
func (m *AssembleRequest) XXX_Size() int {
	return xxx_messageInfo_AssembleRequest.Size(m)
}
func (m *AssembleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssembleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssembleRequest proto.InternalMessageInfo

type AssembleResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssembleResponse) Reset()         { *m = AssembleResponse{} }
func (m *AssembleResponse) String() string { return proto.CompactTextString(m) }
func (*AssembleResponse) ProtoMessage()    {}
func (*AssembleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{9}
}

func (m *AssembleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssembleResponse.Unmarshal(m, b)
}
func (m *AssembleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssembleResponse.Marshal(b, m, deterministic)
}
func (m *AssembleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssembleResponse.Merge(m, src)
}
func (m *AssembleResponse) XXX_Size() int {
	return xxx_messageInfo_AssembleResponse.Size(m)
}
func (m *AssembleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssembleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssembleResponse proto.InternalMessageInfo

func (m *AssembleResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SSSPMessageRequest struct {
	Pair                 []*SSSPMessageStruct `protobuf:"bytes,1,rep,name=pair,proto3" json:"pair,omitempty"`
	CalculateStep        bool                 `protobuf:"varint,2,opt,name=calculateStep,proto3" json:"calculateStep,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SSSPMessageRequest) Reset()         { *m = SSSPMessageRequest{} }
func (m *SSSPMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SSSPMessageRequest) ProtoMessage()    {}
func (*SSSPMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{10}
}

func (m *SSSPMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSSPMessageRequest.Unmarshal(m, b)
}
func (m *SSSPMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSSPMessageRequest.Marshal(b, m, deterministic)
}
func (m *SSSPMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSSPMessageRequest.Merge(m, src)
}
func (m *SSSPMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SSSPMessageRequest.Size(m)
}
func (m *SSSPMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SSSPMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SSSPMessageRequest proto.InternalMessageInfo

func (m *SSSPMessageRequest) GetPair() []*SSSPMessageStruct {
	if m != nil {
		return m.Pair
	}
	return nil
}

func (m *SSSPMessageRequest) GetCalculateStep() bool {
	if m != nil {
		return m.CalculateStep
	}
	return false
}

type SSSPMessageStruct struct {
	NodeID               int64    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Distance             float64  `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSSPMessageStruct) Reset()         { *m = SSSPMessageStruct{} }
func (m *SSSPMessageStruct) String() string { return proto.CompactTextString(m) }
func (*SSSPMessageStruct) ProtoMessage()    {}
func (*SSSPMessageStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{11}
}

func (m *SSSPMessageStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSSPMessageStruct.Unmarshal(m, b)
}
func (m *SSSPMessageStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSSPMessageStruct.Marshal(b, m, deterministic)
}
func (m *SSSPMessageStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSSPMessageStruct.Merge(m, src)
}
func (m *SSSPMessageStruct) XXX_Size() int {
	return xxx_messageInfo_SSSPMessageStruct.Size(m)
}
func (m *SSSPMessageStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_SSSPMessageStruct.DiscardUnknown(m)
}

var xxx_messageInfo_SSSPMessageStruct proto.InternalMessageInfo

func (m *SSSPMessageStruct) GetNodeID() int64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *SSSPMessageStruct) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type SSSPMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSSPMessageResponse) Reset()         { *m = SSSPMessageResponse{} }
func (m *SSSPMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SSSPMessageResponse) ProtoMessage()    {}
func (*SSSPMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{12}
}

func (m *SSSPMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSSPMessageResponse.Unmarshal(m, b)
}
func (m *SSSPMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSSPMessageResponse.Marshal(b, m, deterministic)
}
func (m *SSSPMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSSPMessageResponse.Merge(m, src)
}
func (m *SSSPMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SSSPMessageResponse.Size(m)
}
func (m *SSSPMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SSSPMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SSSPMessageResponse proto.InternalMessageInfo

type SimMessageRequest struct {
	Pair                 []*SimMessageStruct `protobuf:"bytes,1,rep,name=pair,proto3" json:"pair,omitempty"`
	CalculateStep        bool                `protobuf:"varint,2,opt,name=calculateStep,proto3" json:"calculateStep,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SimMessageRequest) Reset()         { *m = SimMessageRequest{} }
func (m *SimMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SimMessageRequest) ProtoMessage()    {}
func (*SimMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{13}
}

func (m *SimMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimMessageRequest.Unmarshal(m, b)
}
func (m *SimMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimMessageRequest.Marshal(b, m, deterministic)
}
func (m *SimMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimMessageRequest.Merge(m, src)
}
func (m *SimMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SimMessageRequest.Size(m)
}
func (m *SimMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimMessageRequest proto.InternalMessageInfo

func (m *SimMessageRequest) GetPair() []*SimMessageStruct {
	if m != nil {
		return m.Pair
	}
	return nil
}

func (m *SimMessageRequest) GetCalculateStep() bool {
	if m != nil {
		return m.CalculateStep
	}
	return false
}

type SimMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimMessageResponse) Reset()         { *m = SimMessageResponse{} }
func (m *SimMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SimMessageResponse) ProtoMessage()    {}
func (*SimMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{14}
}

func (m *SimMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimMessageResponse.Unmarshal(m, b)
}
func (m *SimMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimMessageResponse.Marshal(b, m, deterministic)
}
func (m *SimMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimMessageResponse.Merge(m, src)
}
func (m *SimMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SimMessageResponse.Size(m)
}
func (m *SimMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimMessageResponse proto.InternalMessageInfo

type SimMessageStruct struct {
	PatternId            int64    `protobuf:"varint,1,opt,name=patternId,proto3" json:"patternId,omitempty"`
	DataId               int64    `protobuf:"varint,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Times                int32    `protobuf:"varint,3,opt,name=times,proto3" json:"times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimMessageStruct) Reset()         { *m = SimMessageStruct{} }
func (m *SimMessageStruct) String() string { return proto.CompactTextString(m) }
func (*SimMessageStruct) ProtoMessage()    {}
func (*SimMessageStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{15}
}

func (m *SimMessageStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimMessageStruct.Unmarshal(m, b)
}
func (m *SimMessageStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimMessageStruct.Marshal(b, m, deterministic)
}
func (m *SimMessageStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimMessageStruct.Merge(m, src)
}
func (m *SimMessageStruct) XXX_Size() int {
	return xxx_messageInfo_SimMessageStruct.Size(m)
}
func (m *SimMessageStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_SimMessageStruct.DiscardUnknown(m)
}

var xxx_messageInfo_SimMessageStruct proto.InternalMessageInfo

func (m *SimMessageStruct) GetPatternId() int64 {
	if m != nil {
		return m.PatternId
	}
	return 0
}

func (m *SimMessageStruct) GetDataId() int64 {
	if m != nil {
		return m.DataId
	}
	return 0
}

func (m *SimMessageStruct) GetTimes() int32 {
	if m != nil {
		return m.Times
	}
	return 0
}

type PRMessageRequest struct {
	Pair                 []*PRMessageStruct `protobuf:"bytes,1,rep,name=pair,proto3" json:"pair,omitempty"`
	CalculateStep        bool               `protobuf:"varint,2,opt,name=calculateStep,proto3" json:"calculateStep,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PRMessageRequest) Reset()         { *m = PRMessageRequest{} }
func (m *PRMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PRMessageRequest) ProtoMessage()    {}
func (*PRMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{16}
}

func (m *PRMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PRMessageRequest.Unmarshal(m, b)
}
func (m *PRMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PRMessageRequest.Marshal(b, m, deterministic)
}
func (m *PRMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PRMessageRequest.Merge(m, src)
}
func (m *PRMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PRMessageRequest.Size(m)
}
func (m *PRMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PRMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PRMessageRequest proto.InternalMessageInfo

func (m *PRMessageRequest) GetPair() []*PRMessageStruct {
	if m != nil {
		return m.Pair
	}
	return nil
}

func (m *PRMessageRequest) GetCalculateStep() bool {
	if m != nil {
		return m.CalculateStep
	}
	return false
}

type PRMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PRMessageResponse) Reset()         { *m = PRMessageResponse{} }
func (m *PRMessageResponse) String() string { return proto.CompactTextString(m) }
func (*PRMessageResponse) ProtoMessage()    {}
func (*PRMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{17}
}

func (m *PRMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PRMessageResponse.Unmarshal(m, b)
}
func (m *PRMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PRMessageResponse.Marshal(b, m, deterministic)
}
func (m *PRMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PRMessageResponse.Merge(m, src)
}
func (m *PRMessageResponse) XXX_Size() int {
	return xxx_messageInfo_PRMessageResponse.Size(m)
}
func (m *PRMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PRMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PRMessageResponse proto.InternalMessageInfo

type PRMessageStruct struct {
	NodeID               int64    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	PrVal                float64  `protobuf:"fixed64,2,opt,name=prVal,proto3" json:"prVal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PRMessageStruct) Reset()         { *m = PRMessageStruct{} }
func (m *PRMessageStruct) String() string { return proto.CompactTextString(m) }
func (*PRMessageStruct) ProtoMessage()    {}
func (*PRMessageStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{18}
}

func (m *PRMessageStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PRMessageStruct.Unmarshal(m, b)
}
func (m *PRMessageStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PRMessageStruct.Marshal(b, m, deterministic)
}
func (m *PRMessageStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PRMessageStruct.Merge(m, src)
}
func (m *PRMessageStruct) XXX_Size() int {
	return xxx_messageInfo_PRMessageStruct.Size(m)
}
func (m *PRMessageStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_PRMessageStruct.DiscardUnknown(m)
}

var xxx_messageInfo_PRMessageStruct proto.InternalMessageInfo

func (m *PRMessageStruct) GetNodeID() int64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *PRMessageStruct) GetPrVal() float64 {
	if m != nil {
		return m.PrVal
	}
	return 0
}

type BFSMessageRequest struct {
	Pair                 []*BFSMessageStruct `protobuf:"bytes,1,rep,name=pair,proto3" json:"pair,omitempty"`
	CalculateStep        bool                `protobuf:"varint,2,opt,name=calculateStep,proto3" json:"calculateStep,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BFSMessageRequest) Reset()         { *m = BFSMessageRequest{} }
func (m *BFSMessageRequest) String() string { return proto.CompactTextString(m) }
func (*BFSMessageRequest) ProtoMessage()    {}
func (*BFSMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{19}
}

func (m *BFSMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BFSMessageRequest.Unmarshal(m, b)
}
func (m *BFSMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BFSMessageRequest.Marshal(b, m, deterministic)
}
func (m *BFSMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BFSMessageRequest.Merge(m, src)
}
func (m *BFSMessageRequest) XXX_Size() int {
	return xxx_messageInfo_BFSMessageRequest.Size(m)
}
func (m *BFSMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BFSMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BFSMessageRequest proto.InternalMessageInfo

func (m *BFSMessageRequest) GetPair() []*BFSMessageStruct {
	if m != nil {
		return m.Pair
	}
	return nil
}

func (m *BFSMessageRequest) GetCalculateStep() bool {
	if m != nil {
		return m.CalculateStep
	}
	return false
}

type BFSMessageStruct struct {
	NodeID               int64    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	ParentId             int64    `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Level                int64    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BFSMessageStruct) Reset()         { *m = BFSMessageStruct{} }
func (m *BFSMessageStruct) String() string { return proto.CompactTextString(m) }
func (*BFSMessageStruct) ProtoMessage()    {}
func (*BFSMessageStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{20}
}

func (m *BFSMessageStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BFSMessageStruct.Unmarshal(m, b)
}
func (m *BFSMessageStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BFSMessageStruct.Marshal(b, m, deterministic)
}
func (m *BFSMessageStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BFSMessageStruct.Merge(m, src)
}
func (m *BFSMessageStruct) XXX_Size() int {
	return xxx_messageInfo_BFSMessageStruct.Size(m)
}
func (m *BFSMessageStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_BFSMessageStruct.DiscardUnknown(m)
}

var xxx_messageInfo_BFSMessageStruct proto.InternalMessageInfo

func (m *BFSMessageStruct) GetNodeID() int64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *BFSMessageStruct) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *BFSMessageStruct) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

type BFSMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BFSMessageResponse) Reset()         { *m = BFSMessageResponse{} }
func (m *BFSMessageResponse) String() string { return proto.CompactTextString(m) }
func (*BFSMessageResponse) ProtoMessage()    {}
func (*BFSMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7f08008c4ed518b, []int{21}
}

func (m *BFSMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BFSMessageResponse.Unmarshal(m, b)
}
func (m *BFSMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BFSMessageResponse.Marshal(b, m, deterministic)
}
func (m *BFSMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BFSMessageResponse.Merge(m, src)
}
func (m *BFSMessageResponse) XXX_Size() int {
	return xxx_messageInfo_BFSMessageResponse.Size(m)
}
func (m *BFSMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BFSMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BFSMessageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ShutDownRequest)(nil), "protobuf.shutDownRequest")
	proto.RegisterType((*ShutDownResponse)(nil), "protobuf.shutDownResponse")
	proto.RegisterType((*ExchangeRequest)(nil), "protobuf.exchangeRequest")
	proto.RegisterType((*ExchangeResponse)(nil), "protobuf.exchangeResponse")
	proto.RegisterType((*PEvalRequest)(nil), "protobuf.pEvalRequest")
	proto.RegisterType((*PEvalResponse)(nil), "protobuf.pEvalResponse")
	proto.RegisterType((*IncEvalRequest)(nil), "protobuf.incEvalRequest")
	proto.RegisterType((*IncEvalResponse)(nil), "protobuf.incEvalResponse")
	proto.RegisterType((*AssembleRequest)(nil), "protobuf.assembleRequest")
	proto.RegisterType((*AssembleResponse)(nil), "protobuf.assembleResponse")
	proto.RegisterType((*SSSPMessageRequest)(nil), "protobuf.sSSPMessageRequest")
	proto.RegisterType((*SSSPMessageStruct)(nil), "protobuf.sSSPMessageStruct")
	proto.RegisterType((*SSSPMessageResponse)(nil), "protobuf.sSSPMessageResponse")
	proto.RegisterType((*SimMessageRequest)(nil), "protobuf.simMessageRequest")
	proto.RegisterType((*SimMessageResponse)(nil), "protobuf.simMessageResponse")
	proto.RegisterType((*SimMessageStruct)(nil), "protobuf.simMessageStruct")
	proto.RegisterType((*PRMessageRequest)(nil), "protobuf.pRMessageRequest")
	proto.RegisterType((*PRMessageResponse)(nil), "protobuf.pRMessageResponse")
	proto.RegisterType((*PRMessageStruct)(nil), "protobuf.pRMessageStruct")
	proto.RegisterType((*BFSMessageRequest)(nil), "protobuf.bFSMessageRequest")
	proto.RegisterType((*BFSMessageStruct)(nil), "protobuf.bFSMessageStruct")
	proto.RegisterType((*BFSMessageResponse)(nil), "protobuf.bFSMessageResponse")
}

func init() { proto.RegisterFile("worker_service.proto", fileDescriptor_f7f08008c4ed518b) }

var fileDescriptor_f7f08008c4ed518b = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0xd6, 0xb5, 0x2b, 0x8f, 0x6d, 0x4d, 0xbd, 0x32, 0xba, 0x6c, 0x94, 0x29, 0xe2, 0x30,
	0x0e, 0xeb, 0xa4, 0x21, 0x71, 0xe0, 0x02, 0x8c, 0x6d, 0xa8, 0x48, 0xa0, 0x2a, 0x91, 0xe0, 0x82,
	0x40, 0x6e, 0x62, 0xba, 0xa8, 0x69, 0x1c, 0x62, 0x67, 0xe3, 0x4f, 0xdc, 0x91, 0x3f, 0x01, 0xf6,
	0x77, 0x70, 0x40, 0x71, 0x9c, 0xc4, 0x4d, 0x53, 0x84, 0x7a, 0x6a, 0xbf, 0xf7, 0xe3, 0xf3, 0xfb,
	0xfc, 0xe2, 0x0f, 0xba, 0x37, 0x34, 0x9a, 0x92, 0xe8, 0x2b, 0x23, 0xd1, 0xb5, 0xe7, 0x90, 0x41,
	0x18, 0x51, 0x4e, 0x51, 0x4b, 0xfc, 0x8c, 0xe3, 0x6f, 0xc6, 0xf1, 0xc4, 0xe3, 0x57, 0xf1, 0x78,
	0xe0, 0xd0, 0xd9, 0xc9, 0x84, 0x4e, 0xe8, 0x49, 0x96, 0x11, 0x48, 0x00, 0xf1, 0x2f, 0x6d, 0x34,
	0x3b, 0xd0, 0x66, 0x57, 0x31, 0x3f, 0xa7, 0x37, 0x81, 0x45, 0xbe, 0xc7, 0x84, 0x71, 0xf3, 0x39,
	0xe8, 0x45, 0x88, 0x85, 0x34, 0x60, 0x04, 0x99, 0xb0, 0xe9, 0x71, 0x12, 0x61, 0xee, 0xd1, 0xe0,
	0x43, 0x3c, 0xeb, 0x69, 0x87, 0xda, 0x51, 0xc3, 0x9a, 0x8b, 0x25, 0x54, 0xe4, 0x87, 0x73, 0x85,
	0x83, 0x09, 0xc9, 0xa8, 0x4c, 0xd0, 0x8b, 0x90, 0xa4, 0xda, 0x86, 0x35, 0x3a, 0x15, 0x04, 0x2d,
	0x6b, 0x8d, 0x4e, 0xcd, 0x6d, 0xd8, 0x0c, 0x2f, 0xae, 0xb1, 0x9f, 0xf5, 0x3c, 0x86, 0x2d, 0x89,
	0x97, 0x34, 0xe8, 0xb0, 0xed, 0x05, 0x8e, 0xda, 0xf2, 0x14, 0xda, 0x79, 0x44, 0x36, 0xed, 0x42,
	0x33, 0x0e, 0x5d, 0xcc, 0x89, 0x6c, 0x94, 0x28, 0x19, 0x12, 0x33, 0x46, 0x66, 0x63, 0x5f, 0x1d,
	0xb2, 0x08, 0x2d, 0x39, 0x73, 0x0a, 0x88, 0xd9, 0xf6, 0xe8, 0x3d, 0x61, 0x0c, 0xe7, 0xf2, 0xd0,
	0x09, 0xac, 0x87, 0xd8, 0x8b, 0x7a, 0xda, 0x61, 0xfd, 0xe8, 0xfe, 0xe9, 0xfe, 0x20, 0xbb, 0xea,
	0x81, 0x52, 0x6b, 0xf3, 0x28, 0x76, 0xb8, 0x25, 0x0a, 0xd1, 0x13, 0xd8, 0x72, 0xb0, 0xef, 0xc4,
	0x3e, 0xe6, 0xc4, 0xe6, 0x24, 0xec, 0xad, 0x89, 0x13, 0xe6, 0x83, 0xe6, 0x5b, 0xe8, 0x2c, 0x10,
	0x24, 0x82, 0x02, 0xea, 0x92, 0xe1, 0xb9, 0x98, 0xaa, 0x6e, 0x49, 0x84, 0x0c, 0x68, 0xb9, 0x1e,
	0xe3, 0x38, 0x70, 0x88, 0x60, 0xd3, 0xac, 0x1c, 0x9b, 0x0f, 0x60, 0x67, 0x6e, 0xea, 0x54, 0x9c,
	0xe9, 0x41, 0x87, 0x79, 0xb3, 0x92, 0x96, 0xc1, 0x9c, 0x16, 0x43, 0xd1, 0x92, 0x97, 0xae, 0x20,
	0xa5, 0x0b, 0x48, 0x3d, 0x4a, 0x0e, 0xf0, 0x05, 0xf4, 0x32, 0x2b, 0x3a, 0x80, 0x7b, 0x21, 0xe6,
	0x9c, 0x44, 0xc1, 0xd0, 0x95, 0x12, 0x8b, 0x40, 0xa2, 0xde, 0xc5, 0x1c, 0x0f, 0x5d, 0x71, 0x4c,
	0xdd, 0x92, 0x08, 0x75, 0xa1, 0xc1, 0xbd, 0x19, 0x61, 0xbd, 0xba, 0xf8, 0x20, 0x53, 0x60, 0x4e,
	0x40, 0x0f, 0xad, 0x92, 0xbe, 0xe3, 0x39, 0x7d, 0x7b, 0x85, 0xbe, 0xbc, 0x72, 0x05, 0x79, 0x3b,
	0xd0, 0x51, 0x0e, 0x92, 0xea, 0x5e, 0x42, 0xbb, 0xc4, 0xb9, 0x74, 0x79, 0x5d, 0x68, 0x84, 0xd1,
	0x47, 0xec, 0xcb, 0xcd, 0xa5, 0x20, 0xd9, 0xcf, 0xf8, 0xd2, 0xfe, 0xdf, 0xfd, 0x14, 0xa5, 0x2b,
	0x08, 0xf8, 0x0c, 0x7a, 0xb9, 0xff, 0x5f, 0x5f, 0x5a, 0x88, 0x23, 0x12, 0xf0, 0x7c, 0x0b, 0x39,
	0x4e, 0x84, 0xf8, 0xe4, 0x9a, 0xf8, 0x62, 0x0f, 0x75, 0x2b, 0x05, 0xc9, 0xf6, 0x55, 0x21, 0xe9,
	0xfd, 0x9c, 0xfe, 0x59, 0x87, 0xe6, 0x27, 0x61, 0x62, 0xe8, 0x0d, 0xb4, 0x6c, 0x69, 0x35, 0x48,
	0x59, 0x49, 0xc9, 0x91, 0x0c, 0xa3, 0x2a, 0x25, 0x6f, 0xbb, 0x86, 0x5e, 0x40, 0x63, 0x94, 0xbc,
	0x7d, 0xb4, 0xab, 0x2c, 0x55, 0xb1, 0x07, 0xe3, 0xe1, 0x42, 0x3c, 0xef, 0x7d, 0x05, 0x1b, 0xc3,
	0xd4, 0x39, 0x50, 0xaf, 0xa8, 0x9a, 0xb7, 0x17, 0x63, 0xaf, 0x22, 0x93, 0x33, 0xbc, 0x83, 0xf6,
	0x85, 0xb4, 0x38, 0x29, 0x54, 0x55, 0x52, 0x32, 0x44, 0x55, 0x49, 0xd9, 0x18, 0xcd, 0x5a, 0x72,
	0x1d, 0xaf, 0xa5, 0x13, 0xa9, 0x24, 0x25, 0xc3, 0x52, 0x49, 0xca, 0xc6, 0x65, 0xd6, 0xd0, 0x10,
	0x5a, 0xb6, 0x6d, 0x8f, 0x6c, 0x12, 0xb8, 0xe8, 0xa0, 0xd2, 0x92, 0x32, 0x9e, 0x47, 0x4b, 0xb2,
	0x39, 0xd5, 0x25, 0x6c, 0x30, 0x6f, 0x26, 0x98, 0xf6, 0xab, 0x0c, 0x21, 0x23, 0x3a, 0xa8, 0x4e,
	0x2a, 0xba, 0x9a, 0x23, 0x4b, 0xd0, 0x18, 0x15, 0xef, 0x2e, 0x63, 0xd9, 0xaf, 0xcc, 0xa9, 0xc3,
	0x9c, 0x5d, 0xda, 0xe5, 0x61, 0x16, 0x1e, 0x8a, 0x3a, 0xcc, 0xe2, 0xc7, 0x67, 0xd6, 0xce, 0xf4,
	0xdb, 0xdf, 0xfd, 0xda, 0xed, 0x5d, 0x5f, 0xfb, 0x79, 0xd7, 0xd7, 0x7e, 0xdd, 0xf5, 0xb5, 0x71,
	0x53, 0x34, 0x3c, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x38, 0x24, 0xdd, 0x5d, 0x5b, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerClient interface {
	//service to master
	ShutDown(ctx context.Context, in *ShutDownRequest, opts ...grpc.CallOption) (*ShutDownResponse, error)
	PEval(ctx context.Context, in *PEvalRequest, opts ...grpc.CallOption) (*PEvalResponse, error)
	IncEval(ctx context.Context, in *IncEvalRequest, opts ...grpc.CallOption) (*IncEvalResponse, error)
	ExchangeMessage(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error)
	Assemble(ctx context.Context, in *AssembleRequest, opts ...grpc.CallOption) (*AssembleResponse, error)
	//service to worker
	SSSPSend(ctx context.Context, in *SSSPMessageRequest, opts ...grpc.CallOption) (*SSSPMessageResponse, error)
	SimSend(ctx context.Context, in *SimMessageRequest, opts ...grpc.CallOption) (*SimMessageResponse, error)
	PRSend(ctx context.Context, in *PRMessageRequest, opts ...grpc.CallOption) (*PRMessageResponse, error)
	BFSSend(ctx context.Context, in *BFSMessageRequest, opts ...grpc.CallOption) (*BFSMessageResponse, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) ShutDown(ctx context.Context, in *ShutDownRequest, opts ...grpc.CallOption) (*ShutDownResponse, error) {
	out := new(ShutDownResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Worker/ShutDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) PEval(ctx context.Context, in *PEvalRequest, opts ...grpc.CallOption) (*PEvalResponse, error) {
	out := new(PEvalResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Worker/PEval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) IncEval(ctx context.Context, in *IncEvalRequest, opts ...grpc.CallOption) (*IncEvalResponse, error) {
	out := new(IncEvalResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Worker/IncEval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) ExchangeMessage(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error) {
	out := new(ExchangeResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Worker/ExchangeMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) Assemble(ctx context.Context, in *AssembleRequest, opts ...grpc.CallOption) (*AssembleResponse, error) {
	out := new(AssembleResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Worker/Assemble", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) SSSPSend(ctx context.Context, in *SSSPMessageRequest, opts ...grpc.CallOption) (*SSSPMessageResponse, error) {
	out := new(SSSPMessageResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Worker/SSSPSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) SimSend(ctx context.Context, in *SimMessageRequest, opts ...grpc.CallOption) (*SimMessageResponse, error) {
	out := new(SimMessageResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Worker/simSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) PRSend(ctx context.Context, in *PRMessageRequest, opts ...grpc.CallOption) (*PRMessageResponse, error) {
	out := new(PRMessageResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Worker/PRSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) BFSSend(ctx context.Context, in *BFSMessageRequest, opts ...grpc.CallOption) (*BFSMessageResponse, error) {
	out := new(BFSMessageResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Worker/BFSSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
type WorkerServer interface {
	//service to master
	ShutDown(context.Context, *ShutDownRequest) (*ShutDownResponse, error)
	PEval(context.Context, *PEvalRequest) (*PEvalResponse, error)
	IncEval(context.Context, *IncEvalRequest) (*IncEvalResponse, error)
	ExchangeMessage(context.Context, *ExchangeRequest) (*ExchangeResponse, error)
	Assemble(context.Context, *AssembleRequest) (*AssembleResponse, error)
	//service to worker
	SSSPSend(context.Context, *SSSPMessageRequest) (*SSSPMessageResponse, error)
	SimSend(context.Context, *SimMessageRequest) (*SimMessageResponse, error)
	PRSend(context.Context, *PRMessageRequest) (*PRMessageResponse, error)
	BFSSend(context.Context, *BFSMessageRequest) (*BFSMessageResponse, error)
}

// UnimplementedWorkerServer can be embedded to have forward compatible implementations.
type UnimplementedWorkerServer struct {
}

func (*UnimplementedWorkerServer) ShutDown(ctx context.Context, req *ShutDownRequest) (*ShutDownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutDown not implemented")
}
func (*UnimplementedWorkerServer) PEval(ctx context.Context, req *PEvalRequest) (*PEvalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PEval not implemented")
}
func (*UnimplementedWorkerServer) IncEval(ctx context.Context, req *IncEvalRequest) (*IncEvalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncEval not implemented")
}
func (*UnimplementedWorkerServer) ExchangeMessage(ctx context.Context, req *ExchangeRequest) (*ExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeMessage not implemented")
}
func (*UnimplementedWorkerServer) Assemble(ctx context.Context, req *AssembleRequest) (*AssembleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Assemble not implemented")
}
func (*UnimplementedWorkerServer) SSSPSend(ctx context.Context, req *SSSPMessageRequest) (*SSSPMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSSPSend not implemented")
}
func (*UnimplementedWorkerServer) SimSend(ctx context.Context, req *SimMessageRequest) (*SimMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimSend not implemented")
}
func (*UnimplementedWorkerServer) PRSend(ctx context.Context, req *PRMessageRequest) (*PRMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PRSend not implemented")
}
func (*UnimplementedWorkerServer) BFSSend(ctx context.Context, req *BFSMessageRequest) (*BFSMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BFSSend not implemented")
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_ShutDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).ShutDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Worker/ShutDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).ShutDown(ctx, req.(*ShutDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_PEval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PEvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).PEval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Worker/PEval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).PEval(ctx, req.(*PEvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_IncEval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncEvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).IncEval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Worker/IncEval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).IncEval(ctx, req.(*IncEvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_ExchangeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).ExchangeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Worker/ExchangeMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).ExchangeMessage(ctx, req.(*ExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_Assemble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssembleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Assemble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Worker/Assemble",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Assemble(ctx, req.(*AssembleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_SSSPSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSSPMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).SSSPSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Worker/SSSPSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).SSSPSend(ctx, req.(*SSSPMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_SimSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).SimSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Worker/SimSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).SimSend(ctx, req.(*SimMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_PRSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PRMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).PRSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Worker/PRSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).PRSend(ctx, req.(*PRMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_BFSSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BFSMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).BFSSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Worker/BFSSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).BFSSend(ctx, req.(*BFSMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShutDown",
			Handler:    _Worker_ShutDown_Handler,
		},
		{
			MethodName: "PEval",
			Handler:    _Worker_PEval_Handler,
		},
		{
			MethodName: "IncEval",
			Handler:    _Worker_IncEval_Handler,
		},
		{
			MethodName: "ExchangeMessage",
			Handler:    _Worker_ExchangeMessage_Handler,
		},
		{
			MethodName: "Assemble",
			Handler:    _Worker_Assemble_Handler,
		},
		{
			MethodName: "SSSPSend",
			Handler:    _Worker_SSSPSend_Handler,
		},
		{
			MethodName: "simSend",
			Handler:    _Worker_SimSend_Handler,
		},
		{
			MethodName: "PRSend",
			Handler:    _Worker_PRSend_Handler,
		},
		{
			MethodName: "BFSSend",
			Handler:    _Worker_BFSSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker_service.proto",
}
